### ISSUE TITLE
Release checklist for PACE-HRH V1.0.0

### ISSUE THREAD

**Issue by celiot-IDM** [InstituteforDiseaseModeling/PACE-HRH#149]
- [x] Legal signoff - Doug Bradley
- [x] Repository README - Jen (#148)(#178)
- [x] Inform publicity team
- [x] Rename repository to PACE-HRH
- [x] Set up repository groups and permissions
- [x] Final V1.0.0 build
- [x] Flip switch to make repo public
